---
title: "EDA of mock TCR:pMHC complexes"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
```

```{r}
df = fread("../preprocessing/output/structure.txt", header=T, sep="\t")[tcr_region %in% c("CDR3")]

df$tcr_gene = as.factor(substr(as.character(df$tcr_v_allele), 1, 3))
df$tcr_v_allele = NULL
df$mhc_a_allele = NULL
df$mhc_b_allele = NULL
df$energy = NULL
df$mhc_type = as.factor(df$mhc_type)

df$tcr_region = as.factor(df$tcr_region)
df$aa_tcr = as.factor(df$aa_tcr)
df$aa_antigen = as.factor(df$aa_antigen)
df$species = as.factor(df$species)
df$pdb_id = as.factor(df$pdb_id)

df$contact = df$distance <= 4.5
#df = df[pdb_id != "4p46"] # this one has covlinked peptide

summary(df)
```

Remove bad regions/complexes

```{r}
df.dist.min = df %>%
  group_by(pdb_id, tcr_gene, tcr_region, mhc_type) %>%
  summarize(min_dist = min(distance_CA), mean_dist = mean(distance_CA))

ggplot(df.dist.min, aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type) + 
  theme_bw()

good_regions = df.dist.min %>% filter(min_dist <= 15) %>%
  select(pdb_id, tcr_gene, tcr_region)

good_regions$good_region = T
 
good_pdb = unique(good_regions$pdb_id)

print(good_pdb)

ggplot(subset(df.dist.min, min_dist<=15), aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type) + 
  theme_bw()

df = merge(df, good_regions, all.x = T, by = c("pdb_id", "tcr_gene", "tcr_region"))
df = subset(df, good_region)
```

Load mock data

```{r}
df.mock = fread("../preprocessing/output/mock_structure.txt", header=T, sep="\t")[tcr_region %in% c("CDR1", "CDR2", "CDR3")]
```

```{r}
df.dist.min.m = df.mock %>%
  group_by(pdb_id_a, pdb_id_t, tcr_gene, tcr_region, mhc_type) %>%
  summarize(min_dist = min(distance_CA), mean_dist = mean(distance_CA))

good_regions = df.dist.min.m %>% filter(min_dist <= 15 & min_dist > 3) %>%
  select(pdb_id_a, pdb_id_t, tcr_gene, tcr_region, mhc_type)

good_regions$good_region = T

df.mock = merge(df.mock, good_regions, all.x = T, 
                by = c("pdb_id_a", "pdb_id_t", "tcr_gene", "tcr_region", "mhc_type"))
df.mock = subset(df.mock, good_region)
```

### 1D parameters

Distribution of CA distances from TCR point of view

```{r}
ggplot() +
  geom_boxplot(data=df.mock,aes(x=pos_tcr, group=pos_tcr, y=distance_CA)) +
  geom_boxplot(data=df,aes(x=pos_tcr, group=pos_tcr, y=distance_CA), color="red", fill=NA) +
  facet_wrap(~len_tcr)
```

from antigen point of view

```{r}
ggplot() +
  geom_boxplot(data=df.mock,aes(x=pos_antigen, group=pos_antigen, y=distance_CA)) +
  geom_boxplot(data=df,aes(x=pos_antigen, group=pos_antigen, y=distance_CA), color="red", fill=NA) +
  facet_wrap(~len_antigen)
```

Number of contacts

```{r}
df.contsum = df %>%
  group_by(pdb_id, tcr_gene, tcr_region, mhc_type, len_tcr) %>%
  summarise(contacts = sum(distance <= 4.5)) 
df.contsum$type = "Actual"
df.contsum$pdb_id = NULL
df.contsum = as.data.frame(df.contsum)

df.contsum.m = df.mock %>%
  group_by(pdb_id_a, pdb_id_t, tcr_gene, tcr_region, mhc_type, len_tcr) %>%
  summarise(contacts = sum(distance <= 4.5)) %>%
  dplyr::select(tcr_gene, tcr_region, mhc_type, len_tcr, contacts)
df.contsum.m$type = "Mock"
df.contsum.m$pdb_id_a = NULL
df.contsum.m$pdb_id_t = NULL
df.contsum.m = as.data.frame(df.contsum.m)

ggplot(rbind(df.contsum, df.contsum.m), aes(x=len_tcr, group = interaction(type,len_tcr), y=contacts, color=type)) +
  geom_boxplot() +
  facet_grid(mhc_type~tcr_gene+tcr_region) + 
  scale_color_brewer(palette = "Set1")

ggplot(rbind(df.contsum, df.contsum.m), aes(x=len_tcr, group = interaction(type,len_tcr), y=contacts, color=type)) +
  geom_boxplot() +
  scale_color_brewer(palette = "Set1")
```


### 2D distance and contact plots

```{r}
df.dist = df %>%
  group_by(pos_tcr, pos_antigen, len_antigen, len_tcr, tcr_gene, tcr_region) %>%
  summarize(distance_CA = mean(distance_CA))

df.dist.m = df.mock %>%
  group_by(pos_tcr, pos_antigen, len_antigen, len_tcr, tcr_gene, tcr_region) %>%
  summarize(distance_CA_m = mean(distance_CA))
```

For TRA

```{r}
ggplot(df.dist %>% filter(tcr_gene == "TRA" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(0, 30)) +
  ggtitle("TRA - real")

ggplot(df.dist.m %>% filter(tcr_gene == "TRA" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA_m)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(0, 30)) +
  ggtitle("TRA - mock")

ggplot(merge(df.dist, df.dist.m) %>% filter(tcr_gene == "TRA" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA - distance_CA_m)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(-20, 20)) +
  ggtitle("TRA - difference")
```

For TRB

```{r}
ggplot(df.dist %>% filter(tcr_gene == "TRB" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(0, 30)) +
  ggtitle("TRB - real")

ggplot(df.dist.m %>% filter(tcr_gene == "TRB" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA_m)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(0, 30)) +
  ggtitle("TRB - mock")

ggplot(merge(df.dist, df.dist.m) %>% filter(tcr_gene == "TRB" & tcr_region == "CDR3"), 
       aes(x=pos_tcr, y=pos_antigen, fill = distance_CA - distance_CA_m)) +
  geom_tile() +
  facet_grid(len_antigen~len_tcr, scales="free") +
  scale_fill_gradientn(colors=colorRampPalette(brewer.pal(11, 'Spectral'))(32), limits=c(-10, 10)) +
  ggtitle("TRB - difference")
```
