---
title: "Contacts and affinity"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(mgcv)
library(reshape2)
library(RColorBrewer)
library(stringr)
library(gplots)
```

Load data

```{r}
df = fread("../preprocessing/output/structure.txt", header=T, sep="\t")[tcr_region %in% c("CDR1", "CDR2", "CDR3")]

df$tcr_v_allele = NULL
df$mhc_a_allele = NULL
df$mhc_b_allele = NULL
df$energy = NULL
df$mhc_type = as.factor(df$mhc_type)
df$tcr_gene = as.factor(df$tcr_gene)
df$tcr_region = as.factor(df$tcr_region)
#df$aa_tcr = as.factor(df$aa_tcr)
#df$aa_antigen = as.factor(df$aa_antigen)
df$species = as.factor(df$species)
df$pdb_id = as.factor(df$pdb_id)

df$contact = df$distance <= 4.5
df$aa_pair = with(df, 
  as.factor(ifelse(as.character(aa_tcr) < as.character(aa_antigen), paste(aa_tcr, aa_antigen, sep = "_"), paste(aa_antigen, aa_tcr, sep = "_"))))
df = df[pdb_id != "4p46"]

summary(df)
```

```{r}
df.dist.min = df %>%
  group_by(pdb_id, tcr_gene, tcr_region, mhc_type) %>%
  summarize(min_dist = min(distance_CA))

ggplot(df.dist.min, aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type)

good_regions = df.dist.min %>% filter(min_dist <= 15) %>%
  select(pdb_id, tcr_gene, tcr_region)

good_regions$good_region = T
 
good_pdb = unique(good_regions$pdb_id)

print(good_pdb)

ggplot(subset(df.dist.min, min_dist<=15), aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type)

df = merge(df, good_regions, all.x = T)
df$good_region[is.na(df$good_region)] = F
df = subset(df, pdb_id %in% good_pdb)
summary(df)
```

```{r}
df.cont = df %>%
  group_by(pdb_id, mhc_type, tcr_gene, tcr_region) %>%
  summarize(contacts = sum(contact))

ggplot(df.cont, aes(contacts)) +
  geom_histogram(binwidth = 1) +
  facet_grid(mhc_type~tcr_gene+tcr_region, scales="free_y") +
  theme_bw()
```

```{r}
hydrop = data.frame(
  aa = strsplit("I	V	L	F	C	M	A	W	G	T	S	Y	P	H	N	D	Q	E	K	R", "\t")[[1]],
  h = as.integer(strsplit("1	1	1	1	1	1	1	1	0	0	0	0	0	0	-1	-1	-1	-1	-1	-1", "\t")[[1]])
)

hydrop.2 = expand.grid(aa_tcr = hydrop$aa, aa_antigen = hydrop$aa)

colnames(hydrop) = c("aa_tcr", "h_tcr")
hydrop.2 = merge(hydrop.2, hydrop)

colnames(hydrop) = c("aa_antigen", "h_ag")
hydrop.2 = merge(hydrop.2, hydrop)

hydrop.2$h = with(hydrop.2, h_tcr + h_ag)

hydrop.2 = hydrop.2 %>%
  select(aa_tcr, aa_antigen, h)
```

```{r}
df.cont.2 = merge(df, hydrop.2, by = c("aa_tcr", "aa_antigen"))

df.cont.2 = df.cont.2 %>%
  filter(good_region) %>%
  group_by(pdb_id, mhc_type, tcr_gene, tcr_region, h) %>%
  summarize(contacts = sum(contact), total = n())

ggplot(df.cont.2, aes(x=contacts/total, group = h, color = h)) +
  geom_density() +
  facet_grid(mhc_type~tcr_gene+tcr_region, scales="free_y") +
  theme_bw()
```

```{r}
df.cont.3 = df.cont.2 %>%
  group_by(pdb_id, h) %>%
  summarize(contacts = sum(contacts), total = n()) %>%
  group_by(pdb_id) %>%
  mutate(contact_freq = contacts/sum(contacts))

ggplot(df.cont.3, aes(x=contact_freq, group = h, color = as.factor(h))) +
  geom_density() +
  scale_color_brewer(palette = "RdYlBu") +
  theme_bw()
```

```{r}
df.affinity = read.table("evaluation/atlas_main.txt", header = T, sep = "\t", stringsAsFactors = F) %>%
  filter(MHC_mut == "WT", TCR_mut == "WT", PEP_mut == "WT", true_PDB != "") %>%
  select(true_PDB, DeltaG_kcal_per_mol) %>%
  group_by(true_PDB) %>%
  summarize(pdb_id = tolower(true_PDB[1]), deltaG = mean(as.numeric(DeltaG_kcal_per_mol))) %>%
  select(pdb_id, deltaG)
```

```{r}
df.cont.4 = df.cont.3 %>%
  group_by(pdb_id) %>%
  summarize(contact_freq = sum(h * contacts) / sum(contacts))

df.affinity.contact = merge(df.affinity, df.cont.4)

ggplot(df.affinity.contact, aes(x=contact_freq, y = deltaG)) +
  geom_point(shape=21, color = "black") +
  theme_bw()
```

```{r}
df.affinity.contact = merge(df.affinity, df.cont.3)

ggplot(df.affinity.contact, aes(x=contacts, y = deltaG, color = h)) +
  geom_point() +
  facet_wrap(~pdb_id) +
  theme_bw()
```

```{r}
aa_classes = data.frame(
  aa_type = strsplit("aliphatic,aliphatic,aliphatic,aliphatic,basic,basic,basic,sulfur,sulfur,hydroxyl,hydroxyl,acidic,acidic,amide,amide,G,F,P,W,Y", ",")[[1]],
  aa = strsplit("A,I,L,V,R,H,K,C,M,S,T,D,E,N,Q,G,F,P,W,Y", ",")[[1]]
)

colnames(aa_classes) = c("aa_type_tcr", "aa_tcr")
df = merge(df, aa_classes, by = "aa_tcr")
colnames(aa_classes) = c("aa_type_antigen", "aa_antigen")
df = merge(df, aa_classes, by = "aa_antigen")
```

```{r}
library('scales')
df.dist.table = 
  df %>% filter(distance_CA <= 12) %>%
  group_by(aa_type_tcr, aa_type_antigen) %>%
  summarize(count_close = n())

df.dist.table = merge(df.dist.table,
  df %>% filter(contact) %>%
  group_by(aa_type_tcr, aa_type_antigen) %>%
  summarize(count_contact = n()))

df.dist.table$count_contact[is.na(df.dist.table$count_contact)] = 0
df.dist.table$count_close[is.na(df.dist.table$count_close)] = 0

df.dist.table.2 = df.dist.table
df.dist.table.2$aa_type_tcr = df.dist.table$aa_type_antigen
df.dist.table.2$aa_type_antigen = df.dist.table$aa_type_tcr

df.dist.table = rbind(df.dist.table, df.dist.table.2) %>%
  group_by(aa_type_tcr, aa_type_antigen) %>%
  summarize(count_close = sum(count_close), count_contact = sum(count_contact))

ggplot(df.dist.table, aes(x=aa_type_tcr, y=aa_type_antigen , fill = (count_contact + 1/2) / (count_close + 1/2))) +
  geom_tile() +
  geom_text(aes(label = count_contact))

df.dist.table = df.dist.table %>%
  group_by(aa_type_tcr) %>%
  mutate(row_sum = sum(count_contact)) %>%
  group_by(aa_type_antigen) %>%
  mutate(col_sum = sum(count_contact))
  
ggplot(df.dist.table, aes(x=aa_type_tcr, y=aa_type_antigen, fill = count_contact / row_sum / col_sum)) +
  geom_tile() 
```
