---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(mgcv)
library(reshape2)
library(RColorBrewer)
library(stringr)
library(gplots)
```

Load data

```{r}
df = fread("../preprocessing/output/structure.txt", header=T, sep="\t")[tcr_region %in% c("CDR1", "CDR2", "CDR3")]

df$tcr_v_allele = NULL
df$mhc_a_allele = NULL
df$mhc_b_allele = NULL
df$energy = NULL
df$mhc_type = as.factor(df$mhc_type)
df$tcr_gene = as.factor(df$tcr_gene)
df$tcr_region = as.factor(df$tcr_region)
df$species = as.factor(df$species)
df$pdb_id = as.factor(df$pdb_id)

df$contact = df$distance <= 4.5
df$aa_pair = with(df, 
  as.factor(ifelse(as.character(aa_tcr) < as.character(aa_antigen), paste(aa_tcr, aa_antigen, sep = "_"), paste(aa_antigen, aa_tcr, sep = "_"))))
df = df[pdb_id != "4p46"]

summary(df)
```

```{r}
df.dist.min = df %>%
  group_by(pdb_id, tcr_gene, tcr_region, mhc_type) %>%
  summarize(min_dist = min(distance_CA))

ggplot(df.dist.min, aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type)

good_regions = df.dist.min %>% filter(min_dist <= 15) %>%
  select(pdb_id, tcr_gene, tcr_region)

good_regions$good_region = T
 
good_pdb = unique(good_regions$pdb_id)

print(good_pdb)

ggplot(subset(df.dist.min, min_dist<=15), aes(x=pdb_id, y = min_dist, color = paste(tcr_gene, tcr_region))) +
  geom_point() +
  coord_flip() +
  facet_wrap(~mhc_type)

df = merge(df, good_regions, all.x = T)
df$good_region[is.na(df$good_region)] = F
df = subset(df, pdb_id %in% good_pdb)
summary(df)
```

```{r}
ggplot(df %>% filter(good_region), aes(x=distance_CA, color = contact)) +
  geom_density() +
  scale_x_continuous(limits=c(0,30)) +
  facet_wrap(~aa_tcr)
```