---
title: "Backbone2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(nloptr)

df = read.table("../result/backbone.txt", header = T, sep = "\t") %>%
  mutate(tcr_chain = as.factor(substr(as.character(tcr_v_allele), 1, 3)))

df.dist = read.table("../result/structure.txt", header=T, sep="\t") %>%
  filter(tcr_region %in% c("CDR1", "CDR2", "CDR3")) %>%
  mutate(tcr_chain = as.factor(substr(as.character(tcr_v_allele), 1, 3)))
```

### Sandbox section, or should we rather call it a zoo?

```{r}
ggplot(df %>% filter(tcr_region == "CDR3"), aes(x = pos_tcr / len_tcr, y = z)) +
  geom_line(aes(group = pdb_id, color = len_tcr), alpha = 0.6) +
  geom_smooth() +
  #geom_point(aes(size = y)) +
  facet_grid(tcr_chain ~ mhc_type) +
  theme_bw()
```

```{r}
ggplot(df %>% filter(tcr_region == "CDR3"), aes(x = pos_tcr / len_tcr, y = y)) +
  geom_line(aes(group = interaction(pdb_id, tcr_chain), color = len_tcr), alpha = 0.8) +
  #geom_point(aes(size = y)) +
  scale_color_gradientn(colors=colorRampPalette(rev(brewer.pal(11, 'Spectral')))(32)) +
  facet_wrap(~tcr_chain) +
  theme_dark()
```

```{r}

df.2 = df %>% filter(tcr_region == "CDR3") 
 
df.3 = df.2 %>% 
  filter(pos_tcr == len_tcr - 3) %>%
  mutate(aa_3_term = aa_tcr) %>%
  select(pdb_id, tcr_chain, aa_3_term)

df.2 = merge(df.2, df.3)

df.3 = df.2 %>% 
  filter(pos_tcr == 3) %>%
  mutate(aa_4_head = aa_tcr) %>%
  select(pdb_id, tcr_chain, aa_4_head)

df.2 = merge(df.2, df.3)

ggplot(df.2, aes(x = pos_tcr / len_tcr, y = y)) +
  geom_line(aes(group = interaction(pdb_id, tcr_chain), color = paste(aa_3_term, aa_4_head) == "Q S"), alpha = 0.7) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

## CDR3 section

### Fitting for Z axis

```{r}
calc_z = function(l, L, params = res.fitz$solution) {
  H = params[1] + params[2] * L
  a = params[3]
  b = params[4]
  x = l / (L - 1)
  return(H * x ^ (a - 1) * (1-x) ^ (b - 1) / beta(a, b))
}

obj_z <- function(pars, data){
  delta = with(data, 
       (z - calc_z(pos_tcr, len_tcr, pars)))

  mean(delta^2)
}

x0 = c(10, 0.5, 1.5, 1.5)
lb = c(1, 0, 1.001, 1.001)
ub = c(20, 2, 10, 10)

df.fitz = df %>% 
  filter(tcr_region == "CDR3") %>%
  select(pos_tcr, pdb_id, tcr_chain, len_tcr, z)

res.fitz = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_z,
             data = df.fitz,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e6))

print(res.fitz)
```

```{r}
df.fitz$z_fit = with(df.fitz, calc_z(pos_tcr, len_tcr, res.fitz$solution))

ggplot(df.fitz , aes(x = pos_tcr / (len_tcr - 1), group = interaction(pdb_id, tcr_chain))) +
  geom_line(aes(y = z), alpha = 0.5) +
  geom_line(aes(y = z_fit), alpha = 0.5, color = "red") +
  facet_wrap(~len_tcr) +
  theme_bw()
```

### Fitting for X axis

```{r}
calc_x = function(l, L, params = res.fitx$solution) {
  H = params[1] + params[2] * L
  a = params[3]
  b = params[4]
  d = params[5] # distance from C to Phe
  x = l / (L - 1)
  return(x * d + H * x ^ (a - 1) * (1 - x) ^ (b - 1) / beta(a, b))
}

obj_x <- function(pars, data){
  delta = with(data, 
       (x - calc_x(pos_tcr, len_tcr, pars)))

  mean(delta^2)
}

x0 = c(10, 0.5, 1.5, 1.5, 5)
lb = c(1, 0, 1.001, 1.001, 0)
ub = c(20, 2, 10, 10, 10)

df.fitx = df %>% 
  filter(tcr_region == "CDR3") %>%
  select(pos_tcr, pdb_id, tcr_chain, len_tcr, x)

res.fitx = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_x,
             data = df.fitx,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e6))

print(res.fitx)
```

```{r}
df.fitx$x_fit = with(df.fitx, calc_x(pos_tcr, len_tcr, res.fitx$solution))

ggplot(df.fitx , aes(x = pos_tcr / (len_tcr - 1), group = interaction(pdb_id, tcr_chain))) +
  geom_line(aes(y = x), alpha = 0.5) +
  geom_line(aes(y = x_fit), alpha = 0.5, color = "red") +
  facet_wrap(~len_tcr) +
  theme_bw()
```

### Fitting for Y axis

```{r}
calc_y = function(l, L, params = res.fity$solution) {
  H = params[1] + params[2] * L
  a1 = params[3]
  b1 = params[4]
  a2 = params[5]
  b2 = params[6]
  x = l / (L - 1)
  return(H * (x ^ (a2 - 1) * (1 - x) ^ (b2 - 1) / beta(a2, b2) - x ^ (a1 - 1) * (1 - x) ^ (b1 - 1) / beta(a1, b1)))
}

obj_y <- function(pars, data){
  delta = with(data, 
       (y - calc_y(pos_tcr, len_tcr, pars)))

  mean(delta^2)
}

x0 = c(10, 0.5, 2, 5, 5, 2)
lb = c(1, 0, 1.001, 1.001, 1.001, 1.001)
ub = c(20, 2, 10, 10, 10, 10)

df.fity = df %>% 
  filter(tcr_region == "CDR3") %>%
  select(pos_tcr, pdb_id, tcr_chain, len_tcr, y)

res.fity = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_y,
             data = df.fity,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e6))

print(res.fity)
```

```{r}
df.fity$y_fit = with(df.fity, calc_y(pos_tcr, len_tcr, res.fity$solution))

ggplot(df.fity , aes(x = pos_tcr / (len_tcr - 1), group = interaction(pdb_id, tcr_chain))) +
  geom_line(aes(y = y), alpha = 0.5) +
  geom_line(aes(y = y_fit), alpha = 0.5, color = "red") +
  facet_wrap(~len_tcr) +
  theme_bw()
```

## CDR3 and antigen distances

```{r}
calc_dist = function(l, L, k, K, tcr_chain, mhc_type, params = res.fitdist$solution) {
  # cdr3 coordinates
  x = calc_x(l, L, res.fitx$solution)
  y = calc_y(l, L, res.fity$solution)
  z = calc_z(l, L, res.fitz$solution)
  
  k0 = K/2 + ifelse(tcr_chain == "TRA", params[1], params[2])
  alpha = ifelse(tcr_chain == "TRA", params[3], params[4])
  
  scale = params[5] # aa <> angstrom
  
  xa = res.fitx$solution[5] / 2 + # cys-phe distance
    scale * (k0 - k) * cos(alpha)
  ya = scale * (k - k0) * sin(alpha)
  za = ifelse(mhc_type == "MHCI", params[6], params[7])
  
  return(sqrt((x - xa) ^ 2 + (y - ya) ^ 2 + (z - za) ^ 2))
}

obj_dist <- function(pars, data){
  delta = with(data, 
       (1/distance_CA - 1/calc_dist(pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, mhc_type, pars)))

  mean(delta^2)
}

x0 = c(0, 0, 
       pi/2, pi/2,
       5, 
       20, 20)
lb = c(-10, -10,
       0, 0,
       1,
       5, 5)
ub = c(10, 10,
       2 * pi, 2 * pi, 
       15,
       50, 50)

df.fitdist = df.dist %>% 
  filter(tcr_region == "CDR3" & distance_CA <= 20) %>%
  select(pdb_id, pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, mhc_type, distance_CA) %>% 
  droplevels

res.fitdist = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_dist,
             data = df.fitdist,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e5))

print(res.fitdist)
```

```{r}
df.fitdist$distance_fit = with(df.fitdist, calc_dist(pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, mhc_type, res.fitdist$solution))

ggplot(df.fitdist, aes(x = as.integer(distance_CA), group = as.integer(distance_CA), y = distance_fit)) +
  geom_boxplot() +
  facet_grid(tcr_chain~mhc_type) +
  geom_abline(slope = 1, intercept = 0, color="red", linetype="dashed") +
  scale_x_continuous(limits = c(0, 30)) +
  scale_y_continuous(limits = c(0, 30)) +
  theme_bw()
```

## CDR1 and CDR2

```{r}
ggplot(df %>% filter(tcr_region != "CDR3") , aes(x = pos_tcr / len_tcr, group = interaction(pdb_id, tcr_chain, tcr_region), y = z)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~len_tcr) +
  theme_bw()

ggplot(df %>% filter(tcr_region != "CDR3") , aes(x = pos_tcr / len_tcr, group = interaction(pdb_id, tcr_chain, tcr_region), y = x)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~len_tcr) +
  theme_bw()

ggplot(df %>% filter(tcr_region != "CDR3") , aes(x = pos_tcr / len_tcr, group = interaction(pdb_id, tcr_chain, tcr_region), y = y)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~len_tcr) +
  theme_bw()
```

### Fitting for Z axis

```{r}
calc_z12 = function(l, L, params = res.fitz12$solution) {
  H = params[1] + params[2] * L
  a = params[3]
  b = params[4]
  x = l / (L - 1)
  return(H * x ^ (a - 1) * (1-x) ^ (b - 1) / beta(a, b))
}

obj_z12 <- function(pars, data){
  delta = with(data, 
       (z - calc_z12(pos_tcr, len_tcr, pars)))

  mean(delta^2)
}

x0 = c(10, 0.5, 1.5, 1.5)
lb = c(0, 0, 1.001, 1.001)
ub = c(20, 2, 10, 10)

df.fitz12 = df %>% 
  filter(tcr_region != "CDR3") %>%
  select(pos_tcr, pdb_id, tcr_chain, tcr_region, len_tcr, z)

res.fitz12 = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_z12,
             data = df.fitz12,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e6))

print(res.fitz12)
```

```{r}
df.fitz12$z_fit = with(df.fitz12, calc_z12(pos_tcr, len_tcr, res.fitz12$solution))

ggplot(df.fitz12, aes(x = pos_tcr / (len_tcr - 1), group = interaction(pdb_id, tcr_chain, tcr_region))) +
  geom_line(aes(y = z), alpha = 0.5) +
  geom_line(aes(y = z_fit), alpha = 0.5, color = "red") +
  facet_wrap(~len_tcr) +
  theme_bw()
```

### Fitting for X axis

```{r}
calc_x12 = function(l, L, params = res.fitx12$solution) {
  H = params[1] + params[2] * L 
  x = l / (L - 1)
  return(H * x)
}

obj_x12 <- function(pars, data){
  delta = with(data, 
       (x - calc_x12(pos_tcr, len_tcr, pars)))

  mean(delta^2)
}

x0 = c(10, 0.5)
lb = c(0, 0)
ub = c(20, 2)

df.fitx12 = df %>% 
  filter(tcr_region != "CDR3") %>%
  select(pos_tcr, pdb_id, tcr_chain, tcr_region, len_tcr, x)

res.fitx12 = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_x12,
             data = df.fitx12,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e6))

print(res.fitx12)
```

```{r}
df.fitx12$x_fit = with(df.fitx12, calc_x12(pos_tcr, len_tcr, res.fitx12$solution))

ggplot(df.fitx12, aes(x = pos_tcr / (len_tcr - 1), group = interaction(pdb_id, tcr_chain, tcr_region))) +
  geom_line(aes(y = x), alpha = 0.5) +
  geom_line(aes(y = x_fit), alpha = 0.5, color = "red") +
  facet_wrap(~len_tcr) +
  theme_bw()
```

### CDR3 and antigen distances

```{r}
calc_dist12 = function(l, L, k, K, tcr_chain, tcr_region, mhc_type, params = res.fitdis12t$solution) {
  # cdr3 coordinates
  x = calc_x12(l, L, res.fitx12$solution)
  y = 0
  z = calc_z12(l, L, res.fitz12$solution)
  
  k0 = K/2 + ifelse(tcr_chain == "TRA", 
                    ifelse(tcr_region == "CDR1", params[1], params[2]), 
                    ifelse(tcr_region == "CDR1", params[3], params[4]))
  
  alpha = ifelse(tcr_chain == "TRA", 
                    ifelse(tcr_region == "CDR1", params[5], params[6]), 
                    ifelse(tcr_region == "CDR1", params[7], params[8]))
  
  scale = params[9] # aa <> angstrom
  
  xa = (res.fitx12$solution[1] + res.fitx12$solution[2] * L) / 2 + # cys-phe distance
    scale * (k0 - k) * cos(alpha)
  ya = scale * (k - k0) * sin(alpha)
  za = ifelse(mhc_type == "MHCI", params[10], params[11])
  
  return(sqrt((x - xa) ^ 2 + (y - ya) ^ 2 + (z - za) ^ 2))
}

obj_dist12 <- function(pars, data){
  delta = with(data, 
       (1/distance_CA - 1/calc_dist12(pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, tcr_region, mhc_type, pars)))

  mean(delta^2)
}

x0 = c(0, 0,
       0, 0,
       pi/2, pi/2,
       pi/2, pi/2,
       5, 
       20, 20)
lb = c(-10, -10,
       -10, -10,
       0, 0,
       0, 0,
       1,
       5, 5)
ub = c(10, 10,
       10, 10,
       2 * pi, 2 * pi, 
       2 * pi, 2 * pi, 
       15,
       50, 50)

df.fitdist12 = df.dist %>% 
  filter(tcr_region != "CDR3" & distance_CA <= 20) %>%
  select(pdb_id, pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, tcr_region, mhc_type, distance_CA) %>% 
  droplevels

res.fitdist12 = nloptr(x0 = x0, lb = lb, ub = ub,
             eval_f = obj_dist12,
             data = df.fitdist12,
             opts = list(algorithm = "NLOPT_LN_SBPLX", 
                               maxeval = 1e5))

print(res.fitdist12)
```

```{r}
df.fitdist12$distance_fit = with(df.fitdist12,
                                 calc_dist12(pos_tcr, len_tcr, pos_antigen, len_antigen, tcr_chain, tcr_region, mhc_type, res.fitdist12$solution))

ggplot(df.fitdist12, aes(x = as.integer(distance_CA), group = as.integer(distance_CA), y = distance_fit)) +
  geom_boxplot() +
  facet_grid(mhc_type~tcr_chain+tcr_region) +
  geom_abline(slope = 1, intercept = 0, color="red", linetype="dashed") +
  scale_x_continuous(limits = c(0, 30)) +
  scale_y_continuous(limits = c(0, 30)) +
  theme_bw()
```

